version: "3.9"
services:
  discovery:
    build: ../../Eureka
    ports:
      - "8761:8761"
    image: "discovery-service"

  personnel:
    build: ../../personnel
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/h2
      - spring.datasource.url=jdbc:h2:file:~/test
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.datasource.driver-class-name=org.h2.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.h2.console.settings.web-allow-others=true

    ports:
      - "3000:8580"
    image: "personnel-service"

  zuul:
    build: ../../zuul-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"
  Mongo:
    container_name: Mongo
    image: "mongo:5-focal"
    ports:
      - "27017:27017"
    hostname: Mongo
    depends_on:
      - "Eureka"
  client:
    container_name: client
    image: "client"
    build: ../../ClientMS
    ports:
      - "3939:3939"
    hostname: client
    depends_on:
      - "Eureka"
      - "Mongo"
    command: "node clients/clients.js"
  Aero:
    build: ../../Aero
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/h2
      - spring.datasource.url=jdbc:h2:file:~/test
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.datasource.driver-class-name=org.h2.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.h2.console.settings.web-allow-others=true
    ports:
      - "3002:8080"
    image: "aero-service"

  reservation:
    build: ../../ReservationMS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/h2
      - spring.datasource.url=jdbc:h2:file:./Database/Data/Reservation;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.datasource.driver-class-name=org.h2.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.h2.console.settings.web-allow-others=true

    ports:
      - "3005:8780"
    image: "reservation-service"
